services:
  mesh:
    build:
      context: .
      target: mesh
    ports:
      - "8080:8080"
      - "8443:8443"
    expose:
      - "8080/tcp"
      - "8443/tcp"
    networks:
      - mesh-network

networks:
  mesh-network:
    driver: bridge
